

import java.awt.Color;
import java.awt.Graphics;

public class Formas extends javax.swing.JFrame {

    Color color = null;

    public Formas() {
        initComponents();
        //this.setBounds(0,0, 600,400);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        comboFigura = new javax.swing.JComboBox<>();
        comboColor = new javax.swing.JComboBox<>();
        labelColor = new javax.swing.JLabel();
        labelFigura = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboFigura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Círculo", "Cuadrado", "Triangulo" }));
        comboFigura.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFiguraItemStateChanged(evt);
            }
        });

        comboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amarillo", "Azul", "Rojo" }));
        comboColor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboColorItemStateChanged(evt);
            }
        });

        labelColor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelColor.setText("Color");

        labelFigura.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelFigura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFigura.setText("Figura");

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelColor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboColor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMostrar)
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelColor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnMostrar)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>

    private void comboFiguraItemStateChanged(java.awt.event.ItemEvent evt) {

    }

    private void comboColorItemStateChanged(java.awt.event.ItemEvent evt) {

    }

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {
        if (comboFigura.getItemCount() > 0) {
            int indiceFigura = comboFigura.getSelectedIndex();
            int indiceColor = comboColor.getSelectedIndex();

            switch (indiceFigura) {
                //Circulo
                case 0:
                    switch (indiceColor) {
                        //Amarillo
                        case 0:
                             circulo(this.getGraphics(), color.YELLOW);
                            break;
                        //Azul
                        case 1:
                            circulo(this.getGraphics(), color.BLUE);
                            break;
                        //Rojo
                        case 2:
                            circulo(this.getGraphics(), color.RED);
                            break;
                        default:
                            break;
                    }

                    break;
                //Cuadrado
                case 1:
                    switch (indiceColor) {
                        //Amarillo
                        case 0:
                             cuadrado(this.getGraphics(), color.YELLOW);
                            break;
                        //Azul
                        case 1:
                            cuadrado(this.getGraphics(), color.BLUE);
                            break;
                        //Rojo
                        case 2:
                            cuadrado(this.getGraphics(), color.RED);
                            break;
                        default:
                            break;
                    }
                    break;
                //Rectangulo
                case 2:
                    switch (indiceColor) {
                        //Amarillo
                        case 0:
                             triangulo(this.getGraphics(), color.YELLOW);
                            break;
                        //Azul
                        case 1:
                            triangulo(this.getGraphics(), color.BLUE);
                            break;
                        //Rojo
                        case 2:
                            triangulo(this.getGraphics(), color.RED);
                            break;
                        default:
                            break;
                    }
                    break;
                default:
                    break;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> comboColor;
    private javax.swing.JComboBox<String> comboFigura;
    private javax.swing.JLabel labelColor;
    private javax.swing.JLabel labelFigura;
    // End of variables declaration


    public void circulo(Graphics g, Color color) {
        super.paint(g);
        g.setColor(color);
        g.fillOval(250, 70, 70, 70);

    }
     public void cuadrado(Graphics g, Color color) {
        super.paint(g);
        g.setColor(color);
        g.fillRect(250, 70, 70, 70);
    }
     public void triangulo(Graphics g, Color color) {
        super.paint(g);
        g.setColor(color);
        int vectorX[] = {300, 350, 250};
        int vectorY[] = {70, 140, 140};
        g.fillPolygon(vectorX, vectorY, 3);
    }
}
